[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor = "8qVLNjbke5YVRnna5ZeWVRfCLV5gh4HiuKnuHRdhNXmf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/han/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
