[package]
name = "solana_lottery"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10.3"
solana-program = "1.15.2"
spl-token = { version="3.5.0", features = [ "no-entrypoint" ] }


[lib]
crate-type = ["cdylib", "lib"]



